stages:
  - build
  - test
  - deploy
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
build website:
  stage: build
  image: node
  script:
    - echo $CI_COMMIT_SHORT_SHA
    - npm install
    - npm install -g @angular/cli
    - ng build
    - sed "s/MyApp/MyApp-$CI_COMMIT_SHORT_SHA/" ./dist/MyApp/index.html
  artifacts:
    paths:
      - ./dist
test artifact:
  image: alpine
  stage: test
  script:
    - grep -q 'Hello' ./dist/MyApp/index.html
test website:
  image: node
  stage: test
  script:
    - npm install
    - npm install -g @angular/cli
    - ng serve &
deploy to github:
  stage: deploy
  image: node
  script:
    - npm install
    - npm install -g @angular/cli
    - ng build --prod --output-path docs/My-Angular --base-href /
    - git config --global user.email "Nick@example.com"
    - git config --global user.name "Nick"
    - git add docs
    - git commit -m 'Add docs'
    - git push github master
