stages:
  - build
  - test
  - deploy staging
  - deploy production
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
variables:
  STAGING_DOMAIN: https://marocvi.github.io/My-Angular-Staging
  PRODUCTION_DOMAIN: https://marocvi.github.io/My-Angular/
#build website:
#  stage: build
#  image: node
#  script:
#    - echo $CI_COMMIT_SHORT_SHA
#    - npm install
#    - npm install -g @angular/cli
#    - ng build
#    - sed "s/MyApp/MyApp-$CI_COMMIT_SHORT_SHA/" ./dist/MyApp/index.html
#  artifacts:
#    paths:
#      - ./dist
#test artifact:
#  image: alpine
#  stage: test
#  script:
#    - grep -q 'Hello' ./dist/MyApp/index.html
#test website:
#  image: node
#  stage: test
#  script:
#    - npm install
#    - npm install -g @angular/cli
#    - ng serve &
deploy to staging:
  stage: deploy staging
  environment:
    name: staging
    url: $STAGING_DOMAIN
  image: node
  only:
    - master
  script:
    - git config --global user.email "Nick@example.com"
    - git config --global user.name "Nick"
    - git remote add github https://marocvi:Ahaiproo1*github.com/marocvi/My-Angular-Staging.git
    - git remote -v
    - npm install
    - npm install -g @angular/cli
    - ng build --prod --output-path docs/My-Angular-Staging --base-href /
    - git status
    - git add .
    - git commit -m 'Add docs'
    - git log
    - git show-ref
    - git branch master
    - git checkout master
    - git push -u github master
deploy to production:
  stage: deploy production
  environment:
    name: production
    url: $PRODUCTION_DOMAIN
  when: manual
  allow_failure: true
  image: node
  script:
    - git init
    - git config --global user.email "Nick@example.com"
    - git config --global user.name "Nick"
    - git remote add github https://github.com/marocvi/My-Angular.git
    - git pull github master
    - npm install
    - npm install -g @angular/cli
    - ng build --prod --output-path docs/My-Angular --base-href /
    - git add .
    - git commit -m 'Add docs'
    - git push -u github master
