stages:
  - build
  - test
  - deploy
build website:
  stage: build
  image: node
  script:
    - echo $CI_COMMIT_SHORT_SHA
    - npm install
    - npm install -g @angular/cli
    - ng build
    - sed "s/MyApp/MyApp-$CI_COMMIT_SHORT_SHA/" ./dist/MyApp/index.html
  artifacts:
    paths:
      - ./dist
test artifact:
  image: alpine
  stage: test
  script:
    - grep -q 'MyApp' ./dist/MyApp/index.html
test website:
  image: node
  stage: test
  script:
    - npm install
    - npm install -g @angular/cli
    - ng serve &
deploy to github:
  stage: deploy
  image: node
  script:
    - npm install
    - npm install -g @angular/cli
    - ng build --prod --output-path docs/My-Angular --base-href /
    - git add docs
    - git commit 'Add docs'
    - git push github master
