build website:
  image: node
  script:
    - npm install
    - npm install -g @angular/cli
    - ng build
  artifacts:
    paths:
      - ./dist
test artifact:
  image: alpine
  stage: test
  script:
    - grep -q 'MyApp' ./dist/index.html
test website:
  image: node
  stage: test
  script:
    - npm install
    - npm install -g @angular/cli
    - ng serve
    - curl "http://localhost:4200" | grep -q "MyApp"
