stages:
  - build
  - test
  - deploy
build website:
  stage: build
  image: node
  script:
    - npm install
    - npm install -g @angular/cli
    - ng build
  artifacts:
    paths:
      - ./dist
test artifact:
  image: alpine
  stage: test
  script:
    - grep -q 'MyApp' ./dist/MyApp/index.html
test website:
  image: node
  stage: test
  script:
    - npm install
    - npm install -g @angular/cli
    - ng serve &
deploy to github:
  stage: deploy
  script:
    - npm install lite-server --save-dev
    - ng build --watch
    - lite-server --baseDir="dist/MyApp"
